auctions/urls.py
from django.urls import path

from . import views

app_name = "auctions"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("cards", views.cards_view, name="cards"),
    path("add", views.add, name="add"),
    path("add_comment", views.add_comment, name="add_comment"),
    path("listing_details", views.listing_details_view, name="listing_details"),
    path("watchlist", views.watchlist_view, name="watchlist"),
    path("category_list", views.category_list, name="category_list"),
    path("category_list/<str:category>", views.category_list_redirect, name="category_list_redirect"),
    path("add_to_watchlist", views.add_to_watchlist, name="add_to_watchlist"),
    path("place_bid", views.place_bid, name="place_bid"),
    path("end_listing", views.end_listing, name="end_listing"),
    path("auctions_history", views.auctions_history, name="auctions_history"),
    path("delete_item_watchlist", views.delete_item_watchlist, name="delete_item_watchlist")
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    def __str__(self):
        return f"{self.first_name}"



class Item(models.Model): 
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="item_list")
    title = models.CharField(max_length=64)
    description = models.CharField(max_length=256, blank=True)
    img_url = models.CharField(max_length=256, blank=True)
    starting_bid = models.DecimalField(decimal_places=2, max_digits=8)
    category = models.CharField(max_length=24, default='No Category')
    status = models.BooleanField(default=True)
    def __str__(self):
        return f"{self.title}, {self.description}"

class ItemCategory(models.Model):
    name = models.CharField(max_length=24, blank=False)
    item = models.ForeignKey(Item, blank=True, on_delete=models.CASCADE, related_name="category_list")
    def __str__(self):
        return f"{self.name}"

class Bid(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_bids")
    amount = models.DecimalField(decimal_places=2, max_digits=8)
    items = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="user_bid_items", blank=True)
    def __str__(self):
        return f"{self.amount}"
    
class ItemComment(models.Model):
    text = models.TextField(max_length=512, blank=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="comments_list")
    author = models.ForeignKey(User, on_delete=models.CASCADE)

class Watchlist(models.Model):
    items = models.ForeignKey(Item, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='watchlist_list')

    def __str__(self):
        return f"{self.items}, {self.user}"

class Category(models.Model):
    name = models.CharField(max_length=24, blank=False)
    items = models.ManyToManyField(Item, blank=True, related_name="categories")

    def __str__(self):
        return f"{self.name}"

class AuctionHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="history_user")
    items = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="items_auction_history")

    def __str__(self):
        return f"{self.user.first_name}, {self.items}"

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django import forms
import logging
from django.db import models

from .models import User, Bid, Item, ItemComment, Watchlist, ItemCategory, AuctionHistory
from .utils import utility
import json 
from django.core import serializers
from django.contrib.auth.decorators import login_required

logger = logging.getLogger('mylogger')
#Define forms based on models


class ItemForm(forms.ModelForm):
    class Meta:
        category_choices = [
            ('clothing', 'Clothing'),
            ('toys', 'Toys'),
            ('electronics', 'Electronics'),
            ('art','Art')
        ]
        model = Item
        fields = ['title', 'description', 'img_url', 'starting_bid', 'category']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control',
                                            'id': 'item_title',
                                            'placeholder': 'Item Title'}),
            'description': forms.TextInput(attrs={'class': 'form-control',
                                            'id': 'item_description',
                                            'placeholder': 'Item Description'}),
            'img_url': forms.TextInput(attrs={'class': 'form-control',
                                            'id': 'item_img_url',
                                            'placeholder': 'Image Url'}),
            'starting_bid': forms.NumberInput(attrs={'class': 'form-control',
                                            'id': 'item_starting_bid',
                                            'placeholder': 'Initial Bid'}),   
            'category': forms.Select(choices=category_choices)                                       
        }

class Comment(models.Model):
    comment = models.TextField(max_length=256)

class CommentForm(forms.Form):
    class Meta:
        model = Comment
        fields = ['comment']
        widgets = {
            'comment': forms.Textarea(attrs={
                 'class':"form-control",
                 'id':"textAreaComment",
                 'rows':"2", 'placeholder':"Type a comment"
            })
        }

def index(request):
    #Here in the index page we want to display all active auction listings.
    items = utility.get_items()
    distinct_users = utility.get_users_with_items()
    json_data = serializers.serialize("json", items)
    json_users = json.dumps(distinct_users)
    message=""
    if request.method == 'POST':        
        listing_title = str(request.POST.get("listing_title", False))
        item_ = Item.objects.filter(title=listing_title).get()
        user_ = User.objects.filter(username=request.user.username).get()
        #Search for item in watchlist
        search_item = Watchlist.objects.filter(items=item_, user=user_)
        if len(search_item)==0:
            message="Item added to watchlist"
            Watchlist(items=item_, user=user_).save()
        else:
            message="Item Has already been added to watchlist"
    context = {
        "json" : json_data,
        "users": json_users
    }
    
    if items != None:
        items_with_bids =  Item.objects.filter(user_bid_items__items__isnull=False).distinct()
        bids = []
        for item in items:
            if item in items_with_bids:
                bids.append(Bid.objects.filter(items=item).order_by('amount').last().amount)
            else:
                bids.append(item.starting_bid)
        logger.info(bids)
        items_bids = list(zip(items,bids))
        return render(request, "auctions/index.html",{
            "items":items,
            "items_bids":items_bids,
            "json":json_data,
            "json_users": json_users,
            "commentForm": CommentForm(),
            "message":message
        })
    else:
        logger.info("index get")
        return render(request, "auctions/index.html", {
            "items":items,
        })

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        commentForm = CommentForm(request.POST)
        # if commentForm.is_valid():
            #logger.infor(commentForm)

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })
        username=request.POST["username"]
        email=request.POST["email"]
        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")

def add(request):
    if request.method == 'GET':
        logger.info("Get add")
        return render(request, "auctions/add.html", {
            "new_form": ItemForm()
        })
    else:
        add_item_form = ItemForm(request.POST)
        if add_item_form.is_valid():
            item_title = add_item_form['title'].value()
            item_desc = add_item_form['description'].value()
            item_img_url = add_item_form['img_url'].value()
            item_str_bid = add_item_form['starting_bid'].value()
            item_cat = add_item_form['category'].value()
            
            #Register a new Item to the db
            new_item = Item(user=request.user, 
                            title=item_title,
                            description=item_desc,
                            img_url=item_img_url,
                            starting_bid=item_str_bid,
                            category=item_cat)
            if new_item != None:
                new_item.save()
                message = "Item successfully added to the db"

                #If the item was added successfully, then create a category with that item after making
                #sure it has not already been added.
                # Category.objects.filter(item=new_item)
                item_category = ItemCategory(name=item_cat, item=new_item)
                item_category.save()

            else:
                message = "Failure while saving to the db"
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/add.html", {
            "new_form": ItemForm(),
            "message": "Invalid Data"
            })

def cards_view(request):
    user = User.objects.filter(username=request.user.username).first()
    # bid = Bid.objects.get(user=user)
    item = Item.objects.filter(user=user)[1]
    description = str(item.description)[0:40] + ".."
    return render(request, "auctions/cards.html", {
        "user":user,
        "item":item,
        "description": description
    })

def listing_details_view(request):
    #Get the listing's title to show on this page
    if request.method == 'POST':        
        listing_title = str(request.POST.get("listing_title", False))
        if (str(request.GET.get("message_bid"))):
            message_bid = str(request.GET.get("message_bid"))
        else:
            message_bid="Couldn't place the bid."
        #Get item object matching this string
        item_ = Item.objects.filter(title=listing_title).get()
        owner = item_.user
        #Comments
        comments = item_.comments_list.all()
        #Search for bids
        search_bid = Bid.objects.filter(items=item_)
        own_this_item = False
        if (item_.user.username == request.user.username):
            own_this_item = True
        if len(search_bid)==0 and message_bid!="Couldn't place the bid.":
            return render(request, "auctions/listing_details.html",{
            "item":item_,
            "owner": owner,
            "comments":comments,
            "last_bid":Bid.objects.filter(items=item_).order_by('amount').last(),
            "privilege": own_this_item
            # "bid": bid
        })
        else:
            return render(request, "auctions/listing_details.html",{
            "item":item_,
            "owner": owner,
            "comments":comments,
            "last_bid":Bid.objects.filter(items=item_).order_by('amount').last(),
            "privilege": own_this_item
            # "bid": bid
        })
        

        
    else:
        # logger.info("Listing Details Get")
        listing_title = str(request.GET.get("listing_title", False))
        
        # logger.info("item name" + listing_title)
        item_ = Item.objects.filter(title=listing_title).get()
        owner = item_.user
        comments = item_.comments_list.all()
        if (str(request.GET.get("message_bid"))):
            message_bid = str(request.GET.get("message_bid"))
        else:
            message_bid="Couldn't place the bid."

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}
{% load static %}


{% block body %}


    <h2>Active Listings</h2>
    {%if message %}
                          <p>{{message}}</p>
                          {%endif%}
                          
    {% if items %}
        <div class="container">
            <div class="row">
        {% for item in items_bids %}
              {% if item.0.status %}
                <div class="col-lg-4">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top"   src="{{item.0.img_url}}" alt="Card image cap">
                        <div class="card-body">
                          <h5 class="card-title">
                              <span style="display: block; overflow: hidden; white-space: nowrap; height: 23px; text-overflow: ellipsis;">
                                {{item.0.title}}
                              </span>
                              </h5>
                          <h6 class="card-subtitle mb-2 text-muted">{{ item.0.user.username }}</h6>
                            <p class="card-text">
                                <span id="item-title" style="display: block; overflow: hidden; white-space: nowrap; height: 23px; text-overflow: ellipsis;">
                                   {{item.0.description}}
                                </span>
                            </p>
                          
                          <div style="flex-direction: row; " class="flexbox-container">
                            <label style="font-size: 20px; font-weight: bold; padding-right: 10px;">Bid</label>
                            {% if item.1 %}
                            <label style="font-size: 35px; ">${{item.1}}</label>
                            {% else %}
                            <label style="font-size: 35px; ">${{item.0.starting_bid}}</label>
                            {% endif %}
                            
                          </div>
                          <div style="text-align: center;">
                            <!-- <button onclick="showAlert('{{item.title}}');"  href="#" id="myBtn" class="btn btn-primary" data-toggle="modal">Open</button> -->
                            <form method="POST" action=" {% url 'auctions:listing_details' %} ">
                              {% csrf_token %}
                              <input hidden type="text" value="{{item.0.title}}" name="listing_title">
                              <button   href="#" id="myBtn" class="btn btn-primary" type="submit">Open</button>
                            </form>
                            <form method="POST" action=" {% url 'auctions:index' %} ">
                              {% csrf_token %}
                              <input hidden type="text" value="{{item.0.title}}" name="listing_title">
                              <button   href="#" id="myBtn1" class="btn btn-secondary" type="submit">Add to Watchlist</button>
                            </form>
                          </div>
                          
                          
                        </div>
                    </div>
                </div>
                {% endif %}
        {% endfor %}
        </div>
    </div> 
    {% else %}
          <h4>There's no listing at the moment</h4>
    {% endif %}

    <!-- The Modal -->
    <div class="modal" id="myModal">
        <div class="modal-dialog modal-lg modal-dialog-scrollable">
          <div class="modal-content">
      
            <!-- Modal Header -->
            <div class="modal-header">
                <div style="width: 100%; box-sizing: border-box;">
                    <div class="box">
                        <img id="img_item_modal" height="220px"  src="" alt="Card image cap">
                    </div>

                    <h4 id="modal_title" class="modal-title">{{item.0.title}}</h4>
                    <div style="display: inline-block; position: relative;">
                       <label >Owner: </label> 
                       <label id="username_label">{{user.username}}</label>
                    </div>
                    <div style="">
                        <label >Current Bid: $</label> 
                        <label id="modal_bid"></label>
                    </div>
                </div>
              <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <!-- Modal body -->
            <div class="modal-body">
              <h5>Comments</h5>
             <div class="media-list">
                 <li class="media">
                     <a class="pull-left" href="#">
                        <img class="media-object rounded-circle" height="150px" src="{% static 'auctions/media/alejo_cat.jpeg'%}" alt="profile">
                     </a>
                     <div style="background-color: #E2E2E2; " class="media-body">
                         <div style="padding: 20px; " class="well well-lg">
                             <h4 id="" class="media-heading text-uppercase reviews">{{user.username}}</h4>
                             
                             <ul class="media-date text-uppercase reviews ">
                                <li>22</li>
                                <li>09</li>
                                <li>2014</li>
                             </ul>
                             <p class="media-comment">
                                Great job Alejo, Keep it up!
                             </p>
                             
                         </div>
                     </div>
                 </li>
             </div>
             
             <form method="POST" action="{% url 'auctions:add_comment' %}">
                <div class="form-group">
                    {% csrf_token %}
                    <label for="textAreaComment">New comment</label>
                    <input hidden  type="text" id="uname" name="username" value="{{user.username}}" > 
                    <!-- <textarea class="form-control" id="comment" rows="2" placeholder="Type a comment">USER</textarea> -->
                    <textarea class="form-control" rows="2" placeholder="Type a comment" id="comment", name="comment" value="USER"> </textarea>
                    <!-- {{commentForm}} -->
                    <div style="text-align: right;">
                    <button  id="addComment" type="submit" class="btn btn-secondary" >Comment</button>
                     </div>
                  </div> 
             </form>
             
                                         
            </div>
             <!-- Modal footer -->
             <div class="modal-footer">
                <button id="closeModalBtn" type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
    </div>
    
    <script type="text/javascript">
    var data = {{json|safe}}
    var users = {{json_users|safe}}
    function showAlert(title){
                console.log("hi");
                console.log(title)
                var match_item = data.filter(item => item["fields"].title==title)
                
        
                var modal = document.getElementById("myModal");
                closeModalBtn = document.getElementById("closeModalBtn");
                closeModalBtn.onclick = closeModal;
                modal.style.display = "block";

                box_tag = document.getElementById("img_item_modal");
                username_tag = document.getElementById("username_label");
                modal_title = document.getElementById("modal_title");
                modal_bid = document.getElementById("modal_bid");

                item_user = Object.fromEntries(Object.entries(users).filter(([k,v]) => v===match_item[0]['fields'].user));
                username_tag.innerHTML = Object.keys(item_user)[0];
                modal_title.innerHTML = match_item[0]['fields'].title;
                modal_bid.innerHTML = match_item[0]['fields'].starting_bid;

                img_item_modal.setAttribute("src", match_item[0]['fields'].img_url);

               
                // closeModalBtn = document.getElementById("closeModalBtn");
                // closeModalBtn.onclick = closeModal;
            };
    // function addComment() {
    //     //Add a new comment logic
    //     var txtAreaComment = document.getElementById("commentText");
    //     console.log(txtAreaComment.value);
    //     }
        function closeModal(event){
            var modal = document.getElementById("myModal");
            modal.style.display = "none";
            };
        window.onload = function(){
            // function showAlert(title){
            //     console.log("hi");
            //     console.log(title)
            //     // modal.style.display = "block";
            //     // closeModalBtn = document.getElementById("closeModalBtn");
            //     // closeModalBtn.onclick = closeModal;
            // };
            // var place_bid_btn = document.getElementsByClassName("btn btn-primary");
            // for (var i=0; i<place_bid_btn.length; i++){
            //     place_bid_btn[i].onclick = showAlert;
            // };
            //place_bid_btn.onclick = showAlert;
            // var modal = document.getElementById("myModal");
            // var closeModalBtn;
        
            // function showAlert(event){
            //     console.log("hi");
            //     modal.style.display = "block";
            //     // closeModalBtn = document.getElementById("closeModalBtn");
            //     // closeModalBtn.onclick = closeModal;
        
            // };
        
            function closeModal(event){
              modal.style.display = "none";
            };
        
        };
        </script>


{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
        <link  href="{% static 'auctions/cards.css' %}" rel="stylesheet">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    </head>
   


    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:add' %}">Add Item</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:watchlist' %}">Watchlist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:auctions_history' %}">Auctions History</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:category_list' %}">Categories</a>
            </li>
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/listing_details.html
{% extends "auctions/layout.html"  %}
{% load static %}

{% block body %}

<div class="container-fluid ">
    <div class="row justify-content-md-center">
        <div class="col-lg-10 ">
            <div class="card" >
                <img class="card-img-top" height="600px" src="{{item.img_url}}" alt="Card image cap">
                <div class="card-body">
                  <h5 class="card-title">{{item.title}}</h5>
                  <h6 class="card-subtitle mb-2 text-muted">{{owner.username}}</h6>
                 <div style="height:60px; overflow: auto;">
                    <p class="card-text">{{item.description}}.</p>
                 </div>
                 <div>
                   <form method="POST" action="{% url 'auctions:place_bid' %}">
                     {% csrf_token %}
                     {% if item.status %}
                      <input name="new_bid" placeholder="Bid">
                      <input hidden name="listing_title" value="{{item.title}}" placeholder="">
                      <button href="#" id="myBtn" class="btn btn-primary">Place Bid</button>
                     {% endif %}

                   </form>
                 </div>
                  
                  <div style="flex-direction: row; " class="flexbox-container">
                    <label style="font-size: 20px; font-weight: bold; padding-right: 10px;">Bid</label>
                    {% if last_bid %}
                    <label style="font-size: 35px; ">${{last_bid}}</label>  
                    {% else %}
                    <label style="font-size: 35px; ">${{item.starting_bid}}</label>
                    {% endif %}
                  </div>
                  <div  style="flex-flow: row wrap; " class="flexbox-container">
                    <div class="row">
                      <label style="padding-left: 15px; font-size: 20px; font-weight: bold; ">Status</label>
                      {% if item.status %}
                      <div style="width: 20px; height: 20px; border-radius: 50%; border: 1px solid; background-color:green; opacity: 0.4; margin-top: 5px; margin-left: 10px;"></div>
                      {% else %}
                      <div style="width: 20px; height: 20px; border-radius: 50%; border: 1px solid; background-color:red; opacity: 0.4;"></div>
                      {% endif %}
                    </div>
                    {% if privilege %}
                    <form action="{% url 'auctions:end_listing' %}" method="POST">
                      {%csrf_token%}
                      <input hidden name="listing_title" value="{{item.title}}">
                     <button  type="submit" class="btn btn-warning">Time up</button>
                    </form>
                    {% endif %}
                    
                    <!-- {% if item.status %} -->
                    
                     <!-- {% endif %} -->
                  </div>
                  {% if message_bid %}
                    <p style="font-weight: bold; color: green;">{{message_bid}}</p>
                    {%else%}
                  {%endif%}
                </div>

                
                <div class="modal-body">
                  <h5>Comments</h5>

                  {% for comment in comments %}
                    
                    <div class="media-list">
                      <li class="media">
                          <a class="pull-left" href="#">
                             <img class="media-object rounded-circle" height="150px" src="{% static 'auctions/media/alejo_cat.jpeg'%}" alt="profile">
                          </a>
                          <div style="background-color: #E2E2E2; " class="media-body">
                              <div style="padding: 20px; " class="well well-lg">
                                  <h4 class="media-heading text-uppercase reviews">{{comment.author.username}}</h4>
                                  <ul class="media-date text-uppercase reviews ">
                                     <li>22</li>
                                     <li>09</li>
                                     <li>2014</li>
                                  </ul>
                                  <p class="media-comment">
                                     {{comment.text}}
                                  </p>
                              </div>
                          </div>
                      </li> 
                    </div>
                    {% empty %}
                      <h6>No comment has been added yet :C</h6>
                {% endfor %}
                </div> 

                 <form method="POST" action="{% url 'auctions:add_comment' %}">
                   {% csrf_token%}
                  <div class="form-group" style="padding-top: 5px;">
                    <label for="commentText">New comment</label>
                    <input hidden type="text" value="{{item.title}}" name="listing_title">
                    <input hidden type="text" value="{{owner.username}}" name="owner">
                    <textarea class="form-control" name="commentText" id="commentText" rows="3"></textarea>
                    <div style="text-align: right ;" >
                      <button class="btn btn-secondary">Add Comment</button>
                   </div>
                  </div> 
                 </form>                                                
                </div>
            </div>        
        </div>
    </div>
  </div> 

  <!-- <div class="container-fluid">
    <div class="row justify-content-md-center">
      <div class="col-lg-10">
        <div class="card">
          <p>
            Hi
          </p>
        </div>
      </div>
    </div>
  </div> -->

{% endblock %}